### ISSUE TITLE
gvr-remote-scripting text is black

### ISSUE THREAD

**Issue by thomasflynn** [gearvrf/GearVRf-Demos#113]
The color of the text in the opening TextViewSceneObject that tells you the ip address is black (or very, very dark).  didn't used to be.

**Comment by liaxim** [comment]
So I wasn't imaging this. I think it is what it should be when built with Eclipse..

**Comment by liaxim** [comment]
Fixed now?

**Comment by thomasflynn** [comment]
yep, thanks for the reminder.
