### ISSUE TITLE
Error:(15, 9) error: cannot find symbol method setMain(Camera2RenderscriptManager,String)

### ISSUE THREAD

**Issue by Qamar4P** [gearvrf/GearVRf-Demos#177]
All steps followed and working but this Compilation error in gvrcamera2renderscript sample. please help me.
```
public class Camera2RenderscriptActivity extends GVRActivity 
{
	private Camera2RenderscriptManager mManger;
	
	@Override
    protected void onCreate(Bundle icicle) {
        super.onCreate(icicle);

        mManger = new Camera2RenderscriptManager(this);
**//error is hear, when comment then it run then crash
        setMain(mManger, "gvr.xml");**
    }
	
    @Override
    protected void onPause() {
        super.onPause();
        mManger.onPause();
        finish();
    }
}
```
D:\GearVRProjects\gvr-camera2renderscript\gvrcamera2renderscript\src\main\java\org\gearvrf\gvrcamera2renderscript\Camera2RenderscriptActivity.java
Error:(15, 9) error: cannot find symbol method setMain(Camera2RenderscriptManager,String)
Incremental compilation of 1 classes completed in 0.055 secs.
:gvrcamera2renderscript:compileDebugJavaWithJavac FAILED
Error:Execution failed for task ':gvrcamera2renderscript:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Qamar4P** [comment]
This issue is occured in Android Studio 2.1.1, Window, Gradle plugin 2.1.0, NDK Revision = 11.2.2725575 and NDK r10e
```
compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.samsung.android.gvr.sample"
        minSdkVersion 21
        targetSdkVersion 21
        renderscriptTargetApi 19
    }
```

**Comment by Qamar4P** [comment]
@liaxim @NolaDonato could you guys plz help me to resolve this issue. May be it's due to small error I made somewhere in configuration. I will be thankful

**Comment by deepakrawat22** [comment]
Hi @Qamar4P could you take latest and also apply the pull request #180 and let me know if you still getting the compilation error or crash.

Thanks

**Comment by Qamar4P** [comment]
@deepakrawat22 `setScript(GVRScript,"gvr.xml");` this method is deprecated but yes it's working now and I can change it for other demo projects as well. Thanks for reverting it. Hope that `setMain(Camera2RenderscriptManager,String)` will work in future.

**Comment by Qamar4P** [comment]
@deepakrawat22  can you please tell me why this issue occured. I face this issue again in gvr-renderableview. then I change setScript(GVRScript, "gvr.xml").. then 
UnsatisfiedLinkError .....dex file "/data/data/com.samsung.android.gvr.sample/files/instant-run/dex/slice-VrApi_491353941c2c9b75cc996b6f4147c0dee315da8c-classes.dex", dex file "/data/data/com.samsung.android.gvr.sample/files/instant-run/dex/slice-SystemUtils_05a42f6b39d7deb75ac419c8f8e800ccc0b7d0cb-classes.dex"],nativeLibraryDirectories=[/data/app/com.samsung.android.gvr.sample-1/lib/arm64, /vendor/lib64, /system/lib64, /vendor/lib64, /system/lib64]]] couldn't find "libgvrf.so"
at java.lang.Runtime.loadLibrary(Runtime.java:366)
 at java.lang.System.loadLibrary(System.java:989)
 at org.gearvrf.GVRActivityNative.<clinit>(GVRActivityNative.java:25)

**Comment by liaxim** [comment]
@Qamar4P Doesn't sound like the framework builds for you. Why don't you try the command line build? Run ./gradlew assembleDebug in the gvr-renderable directory and send us the output. Thanks.

**Comment by Qamar4P** [comment]
@liaxim @deepakrawat22  Framework is working for me. Actual the story is 
1). Compiling with `setMain(GVRMain, "gvr.xml");` for first time it run perfectly but for second time it's setMain method not found... cleaning and restarting not working.. again `setScript(GVRScript,"gvr.xml");` start working.. Why this is so. 
2). When I added `compile 'com.github.barteksc:android-pdf-viewer:1.0.0'` to gradle.build. purpose is to render pdf using `GVRPdfView extends PdfView implements GVRView` but then I ran into problem mention above. Can you please help me with that if I push that code to git or?

**Comment by liaxim** [comment]
We can definitely be more helpful if you push a sample project exhibiting the problem. I am having trouble explaining how it can build first time but not second. Tried the sample myself in Android Studio - it builds fine for me.

**Comment by Qamar4P** [comment]
@liaxim here is what I do.. please checkout for any miss configuration [GVR-PdfRendering](https://github.com/Qamar4P/GVR-PdfRendering)

**Comment by liaxim** [comment]
Your code builds fine me. I had to tweak settings.gradle as it seems you are not using the default directory layout that we have; that would be having GearVRf and GearVRf-Demos at the same level.

There is a crash because the pdf library you depend on adds 64-bits native binaries and once Android sees that it assumes your app is 64-bits. But we do not build gvrf for 64-bits (mostly because of Oculus as far as I recall). So make sure you don't have 64-bits binaries in your apk.
