### ISSUE TITLE
gvr-event-sample click event can't receive.

### ISSUE THREAD

**Issue by damengzai** [gearvrf/GearVRf-Demos#182]
touch the pad can't get click event.

**Comment by rahul27** [comment]
Hi @damengzai, are you talking about the "gvr-events" sample?

Could you give me more information about the issue? I just tested the sample and it worked fine for me.

**Comment by damengzai** [comment]
Hi @rahul27 when I run this sample on my phone in Gear VR headset,I touched the touch pad when I gazed on a view(e.g.Button or ListView),there is no event occur (just like the old example in eclipse changed the TextView show).I used it in Android Studio with the newest code.

**Comment by rahul27** [comment]
I have a few questions for you:

* Are you building the GVRf framework yourself or are you using a pre built library? 
* What is the device you are testing on?
* Are you able to scroll the listview? 
* Do you see the blue tick when you tap on the checkbox? 
* It is only an issue with the textview text not being updated?

**Comment by damengzai** [comment]
I have rebuilt the GVRf framework, I used Galaxy S6 edge+.
My issue is the click event is bad,no widget can click.
Also in the GVRf framework's build.gradle file, "OVR_MOBILE_SDK"means the environment variables to the "ovr_sdk_mobile"?

**Comment by damengzai** [comment]
I tried other example,all function work well.But only some example click event can't work.

**Comment by liaxim** [comment]
@damengzai Regarding OVR_MOBILE_SDK - you can optionally set it to the path where your Oculus Mobile SDK is installed. In Android Studio open Settings->Path Variables and add an entry there. Otherwise you need your Oculus Mobile SDK to be in GVRf/ovr_sdk_mobile/.

**Comment by liaxim** [comment]
@damengzai Are you still experiencing problems?

**Comment by rahul27** [comment]
I am not able to recreate the issue at my end. I even tried running it on the GS6 edge plus - it worked fine.

**Comment by damengzai** [comment]
It worked,but I used the new Framework and the old example,Thank you all!

**Comment by liaxim** [comment]
Thank you for the feedback.
