### ISSUE TITLE
how about some 'getting started' documentation?

### ISSUE THREAD

**Issue by RMKD** [gearvrf/GearVRf-Demos#196]
I'd like to see the following in a README for this repository:
* Android Studio 2+ instructions
* command line instructions (can I just set some environment variables and run `ndk-build ...`? `gradle ...`? something else?)
* troubleshooting for common problems (for instance, the unspecific error `"A problem occurred starting process 'command 'ndk-build'"`)

Following [these instructions](http://www.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildInstruct) was not enough to get me past this error.

**Comment by thomasflynn** [comment]
generally, for the demos on the command-line, doing a ./gradlew assembleDebug should be all you need.  I haven't seen the error about ndk-build.  I assume you've checked that ndk-build is in your path?  If so, we'll have to find out more to figure out what you're missing.
For AndroidStudio, I was initially going to reply asking if adding a link to the build instructions would be sufficient, but it looks as if you already found them and ran into trouble.  Did you have trouble other than the ndk-build error?

**Comment by liaxim** [comment]
@RMKD Btw how did you get past the ``A problem occurred starting process 'command 'ndk-build'`` error?

**Comment by RMKD** [comment]
thanks @thomasflynn - understanding that I needed to call `./gradlew assembleDebug` (rather than `gradle build`) was a big help to building on the command line. I then pushed to the device with `adb install ./app/build/outputs/apk/app-debug.apk`. all the examples I've tested seem to crash on start however. Still haven't tracked down the AndroidStudio setup issue.

**Comment by liaxim** [comment]
Can you share with us the logcat output of the crashes?

--
If you want to run without headset you need the VR developer mode; see https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-troublesh-device-run-app-outside/

I assume you have a signature file but it is an important step you may want to include in your notes. See https://developer.oculus.com/osig/
