### ISSUE TITLE
Any demos on viewing a web page?

### ISSUE THREAD

**Issue by arianaa30** [gearvrf/GearVRf-Demos#199]
Is there any demo on how to view a web page? I was trying to use `GVRWebViewSceneObject`, but apparently it is deprecated.

**Comment by rahul27** [comment]
Try gvr-renderableview https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-renderableview

**Comment by thomasflynn** [comment]
also, gvr-sceneobjects: https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-sceneobjects

**Comment by arianaa30** [comment]
Cool. Is there any restrictions on the webpage? There is a video player with bunch of javascripts and whatnot.

**Comment by thomasflynn** [comment]
@mkblx any comments?
I know you can enable javascript.  I believe WebGL is not possible.  Haven't tried with an embedded video player.

**Comment by rahul27** [comment]
The GVRWebView is an extension of android.webkit.WebView. 

The developer website does mention that you can enable javascript and - also supports HTML video using hardware acceleration. 

[WebView](https://developer.android.com/reference/android/webkit/WebView.html)

**Comment by arianaa30** [comment]
I see. Seems like WebView is not that promising. Thanks.

**Comment by liaxim** [comment]
@arianaa30 Can we close the issue or do you have other questions?

**Comment by arianaa30** [comment]
Thanks. You can close it.
