### ISSUE TITLE
Camera Field of View

### ISSUE THREAD

**Issue by endriazizi** [gearvrf/GearVRf-Demos#209]
Hello, 
I am using gvr-360video project I trying to figure out how can change the video's field of view.

I hope someone could help me.

Cheers 

Endri

**Comment by thomasflynn** [comment]
not sure if this is what you want, but you could retrieve the left and right cameras from the camera rig, cast those to GVRPerspectiveCamera and call setFovY().

**Comment by liaxim** [comment]
@endriazizi Was this helpful? Do you have other questions?

**Comment by endriazizi** [comment]
I got this error: Error:Execution failed for task ':framework:cleanNative'.
> A problem occurred starting process 'command 'ndk-build.cmd''

**Comment by liaxim** [comment]
@endriazizi Please use these instructions to specify your NDK and Oculus directories: https://github.com/Samsung/GearVRf/wiki/Build%20Tips

**Comment by liaxim** [comment]
@endriazizi Do you still need help?

**Comment by liaxim** [comment]
Ok, planning to close this tomorrow.

**Comment by endriazizi** [comment]
Yes, thanks a lot




------------------------------

[image: photo]
*Endri Azizi*
Software Developer
 +39 389 9868381 <+39+389+9868381> | endri.azizi@gmail.com |
www.endriazizi.com | Skype: endri.azizi
<#UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_>
<http://it.linkedin.com/in/endriazizi>
<http://www.facebook.com/endri.azizi>  <http://twitter.com/EndriAzizi>
<http://instagram.com/EndriAzizi>
Le informazioni contenute nella presente comunicazione e i relativi
allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte
di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.
Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo
e di informarci immediatamente via e-mail.


2016-07-18 17:00 GMT+02:00 Mihail <notifications@github.com>:
