### ISSUE TITLE
How can I change video url after init SceneObject(for Video)?

### ISSUE THREAD

**Issue by damengzai** [gearvrf/GearVRf-Demos#218]
How can I change video url after init SceneObject(for Video)?

**Comment by liaxim** [comment]
If you are referring to the GVRVideoSceneObject then a getMediaPlayer method is exposed. You should be able to change the dataSource via the mediaPlayer instance. Does this help?

**Comment by damengzai** [comment]
When I change url, if use getMediaPlayer() then change the url has something wrong with the MediaPlayer.But I new another MediaPlayer(used ijkMediaPlayer) and setMediaPlayer(),it works.
Thank you!

**Comment by liaxim** [comment]
Glad that it works. Can we close the issue now? Or could you be more specific about what didn't work when you used getMediaPlayer() to change the url?

**Comment by damengzai** [comment]
@liaxim Thank you! You can close the issue.

**Comment by damengzai** [comment]
Hi,  @liaxim how can I make a Android like toast in Gear VR application?
