### ISSUE TITLE
How to make a menu choice

### ISSUE THREAD

**Issue by endriazizi** [gearvrf/GearVRf-Demos#223]
Hello to everyone,
I am trying to put  a menu selection before video 360 VR is lunched but I down't know how to do it.

Any suggestion? 

I would like to do something like that: [https://www.youtube.com/watch?v=5jH6XblhubE]

**Comment by liaxim** [comment]
Hi, you could use Android Views - see gvr-renderable, gvr-events. Or you could libgdx - see gvr-widgetviewer.

**Comment by endriazizi** [comment]
I got this error: Error:Execution failed for task ':framework:cleanNative'.
> A problem occurred starting process 'command 'ndk-build.cmd''

**Comment by liaxim** [comment]
Please follow the instructions at http://gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildInstruct. More specifically the "Build Configuration for Android Studio" section. Alternatively you could use this https://github.com/Samsung/GearVRf/wiki/Build%20Tips to set up your paths.

**Comment by endriazizi** [comment]
Thanks,

I solved adding this:

ANDROID_NDK_HOME=C:\\Users\\username\\Documents\\Android\\ndk\\android-ndk-r10d
OVR_MOBILE_SDK=E:\\Download\\GearVRf-Demos-master\\GearVRf\\ovr_sdk_mobile

into gradle.properties






------------------------------

[image: photo]
*Endri Azizi*
Software Developer
 +39 389 9868381 <+39+389+9868381> | endri.azizi@gmail.com |
www.endriazizi.com | Skype: endri.azizi
<#UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_>
<http://it.linkedin.com/in/endriazizi>
<http://www.facebook.com/endri.azizi>  <http://twitter.com/EndriAzizi>
<http://instagram.com/EndriAzizi>
Le informazioni contenute nella presente comunicazione e i relativi
allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte
di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.
Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo
e di informarci immediatamente via e-mail.


2016-07-06 16:23 GMT+02:00 Mihail <notifications@github.com>:

**Comment by liaxim** [comment]
Great. Can we close the issue or do you have more questions?

**Comment by endriazizi** [comment]
I'm sorry, now I'am getting this error:
Error:Execution failed for task ':framework:buildNative'.
> Process 'command
'C:\Users\endriazizi\Documents\Android\ndk\android-ndk-r12b/ndk-build.cmd''
finished with non-zero exit value 2

Any suggestion?




------------------------------

[image: photo]
*Endri Azizi*
Software Developer
 +39 389 9868381 <+39+389+9868381> | endri.azizi@gmail.com |
www.endriazizi.com | Skype: endri.azizi
<#UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_>
<http://it.linkedin.com/in/endriazizi>
<http://www.facebook.com/endri.azizi>  <http://twitter.com/EndriAzizi>
<http://instagram.com/EndriAzizi>
Le informazioni contenute nella presente comunicazione e i relativi
allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte
di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.
Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo
e di informarci immediatamente via e-mail.


2016-07-06 16:28 GMT+02:00 Mihail <notifications@github.com>:

**Comment by liaxim** [comment]
Can you try the command line build? Run ``gradlew assembleDebug`` in your project dir. What happens?

**Comment by endriazizi** [comment]
Good day!!!

I am trying to figure out how to go back to the main manu after a click
play with the coursor over the video and if there is any option to do play
and stop while video is on play.

I hope you can halp me




------------------------------

[image: photo]
*Endri Azizi*
Software Developer
 +39 389 9868381 <+39+389+9868381> | endri.azizi@gmail.com |
www.endriazizi.com | Skype: endri.azizi
<#UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_>
<http://it.linkedin.com/in/endriazizi>
<http://www.facebook.com/endri.azizi>  <http://twitter.com/EndriAzizi>
<http://instagram.com/EndriAzizi>
Le informazioni contenute nella presente comunicazione e i relativi
allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte
di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.
Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo
e di informarci immediatamente via e-mail.


2016-07-06 18:08 GMT+02:00 Mihail <notifications@github.com>:

**Comment by endriazizi** [comment]
I my scene I have 4 block and one on the top, I don't know ho to place them
in a way it looks I am surrounded

private GVRContext context;

private static final float QUAD_X = 0.4f;
private static final float QUAD_Y = 0.4f;
private static final float HALF_QUAD_X = QUAD_X / 0.0f;
private static final float HALF_QUAD_Y = QUAD_Y / 0.0f;
private static final float DEPTH = -1f;

//BLACK
layoutSceneObject.getTransform().setPosition(0.0f, 0.0f, DEPTH +0.25f);
layoutSceneObject.getTransform().setRotationByAxis(-35.0f,0.0f,0.0f,0.0f);

//RED
layoutSceneObject2.getTransform().setPosition(0.5f, 0.0f, (DEPTH+0.25f));
layoutSceneObject2.getTransform().setRotationByAxis(35.0f,0.0f,0.0f,0.0f);



//YELLOW
layoutSceneObject4.getTransform().setPosition(-0.5f, 0.0f, (DEPTH+0.45f));
layoutSceneObject4.getTransform().setRotationByAxis(-45.0f,0.0f,-2.0f,0.0f);

//BLUE
layoutSceneObject3.getTransform().setPosition(1.0f, 0.0f, (DEPTH+0.45f));
layoutSceneObject3.getTransform().setRotationByAxis(45.0f,0.0f,-2.0f,0.0f);


//GREEN
layoutSceneObject5.getTransform().setPosition(0.0f, 0.5f, (DEPTH+0.25f));
layoutSceneObject5.getTransform().setRotationByAxis(0.0f,65.0f,0.0f,0.0f);



Thanks





------------------------------

[image: photo]
*Endri Azizi*
Software Developer
 +39 389 9868381 <+39+389+9868381> | endri.azizi@gmail.com |
www.endriazizi.com | Skype: endri.azizi
<#UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_>
<http://it.linkedin.com/in/endriazizi>
<http://www.facebook.com/endri.azizi>  <http://twitter.com/EndriAzizi>
<http://instagram.com/EndriAzizi>
Le informazioni contenute nella presente comunicazione e i relativi
allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte
di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.
Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo
e di informarci immediatamente via e-mail.


2016-07-08 9:34 GMT+02:00 Endri Azizi <endri.azizi@gmail.com>:

**Comment by rahul27** [comment]
You can look at the simple gallery example. That will give you an idea about placing objects in a scene:

https://github.com/gearvrf/GearVRf-Demos/blob/master/gvr-simplegallery/app/src/main/java/org/gearvrf/simplegallery/GalleryMain.java

**Comment by endriazizi** [comment]
This example works good for me but in my case I am working with videos and
I would like to place them like the gallery on this example,

and to handle Play each video per time and that allow me to  have a play
stop and go to the main scene button.

Let me know if u have any suggestion.


Thanks a Lot.

**Comment by rahul27** [comment]
The samples below should help you create a menu:

https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-events
https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-widgetviewer

You could also look at gvr-video, a video control menu should pop up when you click on the video:

https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-video

Let me know if that helps.

**Comment by liaxim** [comment]
@endriazizi Any other questions? Can we close this issue?

**Comment by endriazizi** [comment]
Yes, thanks a lot

Il martedì 12 luglio 2016, Mihail <notifications@github.com> ha scritto:

> @endriazizi <https://github.com/endriazizi> Any other questions? Can we
> close this issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gearvrf/GearVRf-Demos/issues/223#issuecomment-231892948>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI_rumTE0cqoiHm2Fp0mToFr3E4JyHlZks5qUs3YgaJpZM4JEWtD>
> .
>


-- 



------------------------------

[image: photo]
*Endri Azizi*
Software Developer
 +39 389 9868381 <+39+389+9868381> | endri.azizi@gmail.com |
www.endriazizi.com | Skype: endri.azizi
<#SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_>
<http://it.linkedin.com/in/endriazizi>
<http://www.facebook.com/endri.azizi>  <http://twitter.com/EndriAzizi>
<http://instagram.com/EndriAzizi>
Le informazioni contenute nella presente comunicazione e i relativi
allegati possono essere riservate e sono, comunque, destinate
esclusivamente alle persone o alla Società sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte
di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi
dell'art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.
Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo
e di informarci immediatamente via e-mail.
