### ISSUE TITLE
gvr-solarsystem GVRSceneObject cannot have multiple parents

### ISSUE THREAD

**Issue by deepakrawat22** [gearvrf/GearVRf-Demos#237]
`07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err: java.lang.UnsupportedOperationException: GVRSceneObject cannot have multiple parents
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at org.gearvrf.GVRSceneObject.addChildObject(GVRSceneObject.java:754)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at org.gearvrf.GVRSceneObject.addChildObject(GVRSceneObject.java:786)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at org.gearvrf.solarsystem.SolarMain.onInit(SolarMain.java:125)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at org.gearvrf.GVRViewManager$3$1.run(GVRViewManager.java:678)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-13 15:21:59.116 23395-23427/org.gearvrf.solarsystem W/System.err:     at android.os.Looper.loop(Looper.java:158)
07-13 15:21:59.126 23395-23427/org.gearvrf.solarsystem W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by rahul27** [comment]
Related to https://github.com/Samsung/GearVRf/issues/692

**Comment by rahul27** [comment]
Lets track this issue here:

Samsung/GearVRf#704
