### ISSUE TITLE
GVR-Collision App crash

### ISSUE THREAD

**Issue by apjagdale** [gearvrf/GearVRf-Demos#246]
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err: java.lang.UnsupportedOperationException: GVRSceneObject cannot have multiple parents
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVRSceneObject.addChildObject(GVRSceneObject.java:754)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVRCameraRig.attachToParent(GVRCameraRig.java:346)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.gvrcollision.CollisionMain.onInit(CollisionMain.java:106)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
07-15 01:10:08.367 23892-24016/com.samsung.android.gvr.sample D/GVRAndroidResource: Looking for compressed header
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVRViewManager$3$1.run(GVRViewManager.java:678)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at android.os.Looper.loop(Looper.java:145)
07-15 01:10:08.367 23892-23970/com.samsung.android.gvr.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rahul27** [comment]
Lets track this issue here:

Samsung/GearVRf#704
