### ISSUE TITLE
GVR-Nonglthreadupdate App crash

### ISSUE THREAD

**Issue by apjagdale** [gearvrf/GearVRf-Demos#247]
07-15 01:19:09.517 7497-7556/org.gearvrf.nontlthreadupdate D/gvrf:   # 0: 0xa1c18858  _Z15printStackTracej
                                                                     # 1: 0xa1c140f4  _ZN3gvr22CustomPostEffectShaderC1ESsSs
                                                                     # 2: 0xa1bfb890  Java_org_gearvrf_NativePostEffectShaderManager_addCustomPostEffectShader
07-15 01:19:09.517 7497-7556/org.gearvrf.nontlthreadupdate E/gvrf: fatal error: no deleter associated with this thread!
07-15 01:19:09.517 7497-7556/org.gearvrf.nontlthreadupdate A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7556 (gvrf-main)
07-15 01:19:10.157 7497-7561/org.gearvrf.nontlthreadupdate I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.

**Comment by rahul27** [comment]
Here is a related issue:

https://github.com/Samsung/GearVRf/issues/667

Could you revert the sample to use GVRScript instead of GVRMain till the issue is fixed?

**Comment by liaxim** [comment]
#255 fixes it
