### ISSUE TITLE
GVR-Opacityanigallery App crash

### ISSUE THREAD

**Issue by apjagdale** [gearvrf/GearVRf-Demos#248]
07-15 01:23:02.177 7734-7755/org.gearvrf.opacityanigallery E/MediaPlayer: Should have subtitle controller already set
07-15 01:23:02.187 7734-7755/org.gearvrf.opacityanigallery D/gvrf:   # 0: 0xaed77858  _Z15printStackTracej
                                                                     # 1: 0xaed730f4  _ZN3gvr22CustomPostEffectShaderC1ESsSs
                                                                     # 2: 0xaed5a890  Java_org_gearvrf_NativePostEffectShaderManager_addCustomPostEffectShader
07-15 01:23:02.187 7734-7755/org.gearvrf.opacityanigallery E/gvrf: fatal error: no deleter associated with this thread!
07-15 01:23:02.187 7734-7755/org.gearvrf.opacityanigallery A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7755 (gvrf-main)

**Comment by rahul27** [comment]
Here is a related issue:

https://github.com/Samsung/GearVRf/issues/667

Could you revert the sample to use GVRScript instead of GVRMain till the issue is fixed?

**Comment by liaxim** [comment]
#255 fixes it
