### ISSUE TITLE
GVR-3dcursor App crash

### ISSUE THREAD

**Issue by apjagdale** [gearvrf/GearVRf-Demos#249]
07-15 01:27:38.547 7991-8012/org.gearvrf.io.cursorsimple W/System.err: java.lang.UnsupportedOperationException: GVRSceneObject cannot have multiple parents
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at org.gearvrf.GVRSceneObject.addChildObject(GVRSceneObject.java:754)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at org.gearvrf.GVRScene.addSceneObject(GVRScene.java:111)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at org.gearvrf.io.cursorsimple.CursorMain.onInit(CursorMain.java:81)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at org.gearvrf.GVRViewManager$3$1.run(GVRViewManager.java:678)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at android.os.Looper.loop(Looper.java:145)
07-15 01:27:38.557 7991-8012/org.gearvrf.io.cursorsimple W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rahul27** [comment]
Lets hold off on reporting new issues on the same exception.

**Comment by rahul27** [comment]
Lets track this issue here:

https://github.com/Samsung/GearVRf/issues/704
