### ISSUE TITLE
Crash in gvr-opacityanigallery

### ISSUE THREAD

**Issue by deepakrawat22** [gearvrf/GearVRf-Demos#252]
`07-14 17:29:08.319 397-397/? A/DEBUG:     r0 00000000  r1 000021d8  r2 00000006  r3 9fc3f978
07-14 17:29:08.319 397-397/? A/DEBUG:     r4 9fc3f980  r5 9fc3f930  r6 00000058  r7 0000010c
07-14 17:29:08.319 397-397/? A/DEBUG:     r8 9fc3eed8  r9 adc4ea10  sl adc4e9f8  fp 9fc3eedc
07-14 17:29:08.319 397-397/? A/DEBUG:     ip 00000006  sp 9fc3edb0  lr b6d20c01  pc b6d22ff0  cpsr 400f0010
07-14 17:29:08.349 397-397/? A/DEBUG: backtrace:
07-14 17:29:08.349 397-397/? A/DEBUG:     #00 pc 00041ff0  /system/lib/libc.so (tgkill+12)
07-14 17:29:08.349 397-397/? A/DEBUG:     #01 pc 0003fbfd  /system/lib/libc.so (pthread_kill+32)
07-14 17:29:08.349 397-397/? A/DEBUG:     #02 pc 0001c397  /system/lib/libc.so (raise+10)
07-14 17:29:08.349 397-397/? A/DEBUG:     #03 pc 00019615  /system/lib/libc.so (__libc_android_abort+34)
07-14 17:29:08.349 397-397/? A/DEBUG:     #04 pc 00017568  /system/lib/libc.so (abort+4)
07-14 17:29:08.349 397-397/? A/DEBUG:     #05 pc 00116f1b  /data/app/org.gearvrf.opacityanigallery-1/lib/arm/libgvrf.so (_ZN9__gnu_cxx27__verbose_terminate_handlerEv+226)
07-14 17:29:08.349 397-397/? A/DEBUG:     #06 pc 000e6d85  /data/app/org.gearvrf.opacityanigallery-1/lib/arm/libgvrf.so (_ZN10__cxxabiv111__terminateEPFvvE+4)
07-14 17:29:08.349 397-397/? A/DEBUG:     #07 pc 000e6df9  /data/app/org.gearvrf.opacityanigallery-1/lib/arm/libgvrf.so (_ZSt9terminatev+8)
07-14 17:29:08.349 397-397/? A/DEBUG:     #08 pc 000e10a8  /data/app/org.gearvrf.opacityanigallery-1/lib/arm/libgvrf.so (_ZN3gvr22CustomPostEffectShaderC1ESsSs+1316)
07-14 17:29:08.349 397-397/? A/DEBUG:     #09 pc 000c884c  /data/app/org.gearvrf.opacityanigallery-1/lib/arm/libgvrf.so (Java_org_gearvrf_NativePostEffectShaderManager_addCustomPostEffectShader+292)
07-14 17:29:08.349 397-397/? A/DEBUG:     #10 pc 001e42f3  /data/data/org.gearvrf.opacityanigallery/cache/slice-intermediates-exploded-aar-framework-debug_345b784d0b6927d70bcc7d860a03fa69eda33508-classes.dex (offset 0x16e000) (int org.gearvrf.NativePostEffectShaderManager.addCustomPostEffectShader(long, java.lang.String, java.lang.String)+142)
07-14 17:29:08.349 397-397/? A/DEBUG:     #11 pc 001bb083  /data/data/org.gearvrf.opacityanigallery/cache/slice-intermediates-exploded-aar-framework-debug_345b784d0b6927d70bcc7d860a03fa69eda33508-classes.dex (offset 0x16e000) (org.gearvrf.GVRCustomPostEffectShaderId org.gearvrf.GVRPostEffectShaderManager.addShader(java.lang.String, java.lang.String)+126)
07-14 17:29:08.349 397-397/? A/DEBUG:     #12 pc 001bafd5  /data/data/org.gearvrf.opacityanigallery/cache/slice-intermediates-exploded-aar-framework-debug_345b784d0b6927d70bcc7d860a03fa69eda33508-classes.dex (offset 0x16e000) (java.lang.Object org.gearvrf.GVRPostEffectShaderManager.addShader(java.lang.String, java.lang.String)+56)
07-14 17:29:08.349 397-397/? A/DEBUG:     #13 pc 0017f659  /data/data/org.gearvrf.opacityanigallery/cache/slice-intermediates-exploded-aar-framework-debug_345b784d0b6927d70bcc7d860a03fa69eda33508-classes.dex (offset 0x16e000) (java.lang.Object org.gearvrf.GVRBaseShaderManager.addShader(java.io.InputStream, java.io.InputStream)+164)
07-14 17:29:08.349 397-397/? A/DEBUG:     #14 pc 0017f581  /data/data/org.gearvrf.opacityanigallery/cache/slice-intermediates-exploded-aar-framework-debug_345b784d0b6927d70bcc7d860a03fa69eda33508-classes.dex (offset 0x16e000) (java.lang.Object org.gearvrf.GVRBaseShaderManager.addShader(int, int)+132)
07-14 17:29:08.349 397-397/? A/DEBUG:     #15 pc 000138ab  /data/data/org.gearvrf.opacityanigallery/cache/slice-slice_4-classes.dex (offset 0x13000) (void org.gearvrf.opacityanigallery.CustomPostEffectShaderManager.<init>(org.gearvrf.GVRContext)+390)
07-14 17:29:08.349 397-397/? A/DEBUG:     #16 pc 0001ee95  /data/data/org.gearvrf.opacityanigallery/cache/slice-slice_4-classes.dex (offset 0x13000) (void org.gearvrf.opacityanigallery.GalleryMain.onInit(org.gearvrf.GVRContext)+2408)
07-14 17:29:08.349 397-397/? A/DEBUG:     #17 pc 000e6411  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
07-14 17:29:08.349 397-397/? A/DEBUG:     #18 pc 004037cd  /system/lib/libart.so (art_quick_invoke_stub+188)
07-14 17:29:08.349 397-397/? A/DEBUG:     #19 pc 00102284  [stack:8664]`

**Comment by liaxim** [comment]
#255 fixes it
