### ISSUE TITLE
Resume does not work on all apps(probably)

### ISSUE THREAD

**Issue by apjagdale** [gearvrf/GearVRf-Demos#264]
Putting head set on and taking it off for around 30 seconds. Again putting it on shows a freezed app.

Tried apps:
GVRCube, GVRWidget, GVRModelViewer and Imersivepedia

**Comment by liaxim** [comment]
@apjagdale Do you still observe this issue?

**Comment by apjagdale** [comment]
@liaxim Having experimental plugin changes. I ran eye-picking demo. Still the same issue.

**Comment by liaxim** [comment]
Tried gvr-immersivepedia. Works fine on S8. Planning to close in few days. @apjagdale You could retest if you have time. Thanks.

**Comment by apjagdale** [comment]
@liaxim Works. Tested on S7 and S8.

**Comment by liaxim** [comment]
Awesome.
