### ISSUE TITLE
How to Play mp4 Video in Android Using Remote URL

### ISSUE THREAD

**Issue by endriazizi** [gearvrf/GearVRf-Demos#271]
Hi there,
I have one question,
How to Play mp4 Video in Android Using Remote URL?
I would like to host my  360 videos onto an hosting and build an android app that I can play theme remotely without downloading them.

Thanks a lot

**Comment by deepakrawat22** [comment]
HI @endriazizi by "play remotely without downloading" did you mean you want to stream the video like YouTube ?

**Comment by deepakrawat22** [comment]
You can use GVRVideoSceneObject along with MediaPlayer which support streaming from URL also.

**Comment by thomasflynn** [comment]
in case it wasn't clear, call the media player's setDataSource() method with the Uri of the video you want to play.

**Comment by liaxim** [comment]
@endriazizi Do you have other questions? Can we close this issue?

**Comment by endriazizi** [comment]
You Can Close The issue
Thanks

Il 10/Ago/2016 17:22, "Mihail" <notifications@github.com> ha scritto:
