### ISSUE TITLE
Build issues and suggestions

### ISSUE THREAD

**Issue by liaxim** [gearvrf/GearVRf-Demos#275]
1. The demos instructions have to be updated to reflect the use of the aar. All those environment variables should be removed and the use of the properties in gradle.properties explained.

2. The hard-coded reference to framework-debug.aar under gearvrf-libs is less than ideal. We need to come up with a way to pick up whatever files are under that folder without the user having to rename anything.

3. As part of the demo build we can and should automatically copy the Oculus dependencies for the user; as long as the user has specified correctly OVR_MOBILE_SDK in gradle.properties.

**Comment by rahul27** [comment]
Should we add something like this to automatically add the framework module (if present)?

It would make it easier to build and test framework changes:

https://github.com/rahul27/GearVRf-Demos/commit/3b4b2277e1bb4e913529eb80a38fcb2b0ee48362

**Comment by liaxim** [comment]
Looks promising. Let me test it some time today. We should try to move the build changes to the samples to the common.gradle file..

**Comment by rahul27** [comment]
I will update my commit after the common.gradle changes.

**Comment by rahul27** [comment]
Here is an updated commit:

https://github.com/rahul27/GearVRf-Demos/commit/9111a7dce819f3e4eed32649e51051e525b187a5

**Comment by liaxim** [comment]
@rahul27 I was recently thinking the other way around, in a way. An uber-project for us that includes all libraries and all the samples. Somewhere in the framework repo, out of the way of end users. Eventually we should stop complicating the demos since they are meant as templates for end-users, to large extent. What do you think?

**Comment by Vittalbabu** [comment]
Sounds like a good idea. Makes testing easier.

**Comment by liaxim** [comment]
Planning to close this one. @rahul27 Any opinion?

You can debug the samples as easily if you just attach the source code for the framework-debug.aar. Java debugging of course.
