### ISSUE TITLE
gvr-camera2renderscript preview stop

### ISSUE THREAD

**Issue by vincentchung** [gearvrf/GearVRf-Demos#276]
I had merged GVRf 3.0.1 with OVR SDK 1.0.3. And Got the APK.
But the preview is stop at the begin. But the app is still working from the log. I can see the log is keeping printing out.

I also had tried other apk with the same way. They are working fine in my Note5.

Anyone had tried the app?

**Comment by rahul27** [comment]
Looks like the app is broken at the moment. I see the following log

````
07-29 10:00:13.840 24430-24430/com.samsung.android.gvr.sample I/GVRViewManager: camera rig yaw reset
                                                                                
                                                                                [ 07-29 10:00:13.860 24430:24472 D/         ]
                                                                                MALI GL_COMPILE_STATUS is not GL_TRUE, 0
07-29 10:00:13.860 24430-24472/com.samsung.android.gvr.sample E/gvrf: Could not compile shader 35632:
                                                                      2:1: P0003: Extension 'GL_OES_EGL_image_external' not supported
                                                                      2:3: L0001: Expected token '{', found 'identifier'
07-29 10:00:13.860 24430-24472/com.samsung.android.gvr.sample A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 24472 (GLThread 520)
````

**Comment by thomasflynn** [comment]
from the log, it sounds like the fragment shader is missing the:
#extension GL_OES_EGL_image_external : require

at the top of the shader

**Comment by rahul27** [comment]
Is this the line?

https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/framework/src/main/jni/shaders/material/oes_shader.cpp#L58

**Comment by thomasflynn** [comment]
that would be the line.  can you run the opengl tracer and verify that shader is coming through unaltered?

**Comment by vincentchung** [comment]
I found the error log at launching the app
com.samsung.android.gvr.sample E/RenderScript: Unable to open shared library (/data/user/0/com.samsung.android.gvr.sample/code_cache/com.android.renderscript.cache/librs.mono.so): (null)


I lost the mono.so file?

**Comment by liaxim** [comment]
@vincentchung librs.mono.so is part of the android runtime and we do not include it in the apk.

How did you build the sample (Eclipse or AS)?

Would you mind making sure you are building using the latest version of the Android Build Tools? I have seen references to issues with renderScript and older versions of the Build Tools.

**Comment by vincentchung** [comment]
I add model.contains("SM-N9208") for set mNeedYuvConversion= true.
The apk works now. that's the root cause in my note5.

**Comment by liaxim** [comment]
Good catch. Thank you. We will make the change to the sample.

**Comment by liaxim** [comment]
Fix in https://github.com/gearvrf/GearVRf-Demos/pull/293

**Comment by liaxim** [comment]
@vincentchung If there are no more problems, can we close this issue?

**Comment by vincentchung** [comment]
sure!!
