### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by knnnrd** [gearvrf/GearVRf-Demos#277]
Hello,
I'm trying to run some of the sample projects but I keep seeing a black screen after I built the project with android studio.

I have followed these steps: [http://wiki.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#SampleApps](url)
I have tried both prebuilt and from source and I have included the oculussig file in app/src/main/assets
I'm on ubuntu 16.04 with linux kernel 4.6.2

Any idea on what is happening?
Thanks in advance

**Comment by liaxim** [comment]
Hi, would you mind sharing logs with us? Are you seeing the black screen while docked in GearVR?

**Comment by knnnrd** [comment]
Yes I see it while docked in gear vr. There is also something that look like White text but it's too far to the side so I can't read what it says.
Where can I find those logs (I'm very inexperiences in android development).

**Comment by liaxim** [comment]
Run your app. Afterwards run ``adb logcat -v threadtime -d > logs.txt`` from the command line.

**Comment by knnnrd** [comment]
This is the log file
[logs.txt](https://github.com/gearvrf/GearVRf-Demos/files/393082/logs.txt)

**Comment by knnnrd** [comment]
Just to let you know, I managed to get the samples working. I started from scratch and followed the installation guide again and now it's working. Probably missed something the first time.
