### ISSUE TITLE
gvr-transparency test unaffected by culling

### ISSUE THREAD

**Issue by NolaDonato** [gearvrf/GearVRf-Demos#307]
This test toggles frustum culling to change what is displayed. This doesn't work anymore. The app does get the touch event and toggle frustum culling but the display does not change.

**Comment by deepakrawat22** [comment]
@NolaDonato I will check this issue.

**Comment by liaxim** [comment]
@deepakrawat22 This is what I have found out about this issue thus far: https://github.com/Samsung/GearVRf/pull/903

**Comment by deepakrawat22** [comment]
@liaxim With the pull request https://github.com/Samsung/GearVRf/pull/903 now it will show Hello_World! even before the tap. Is it acceptable behavior ?

**Comment by liaxim** [comment]
@deepakrawat22 In my opinion it is. Why should the transparency work differently if culling is off or on?

**Comment by deepakrawat22** [comment]
I saw this comment in the app:
``` * Transparency sorting will only work when frustum culling is enabled.  (the sorting relies on distance from the camera which is only calculated when culling is enabled).
```

**Comment by thomasflynn** [comment]
and that was true for the previous implementation.  Mihail has improved that so frustum culling is no longer a requirement.  One thing I'd really like to see scrutinized with this check-in is the compare function.  that function has to satisfy a lot of requirements.

**Comment by thomasflynn** [comment]
sorry, i was referring to the compare function in the framework pull request (https://github.com/Samsung/GearVRf/pull/903), but i'm sure you figured that out.

**Comment by liaxim** [comment]
Transparency sorting no longer needs culling enabled.
