### ISSUE TITLE
Dexing fails

### ISSUE THREAD

**Issue by rincewindcz** [gearvrf/GearVRf-Demos#322]
Hello, 
I'm currently trying to get these examples running but unfortunately for some reason I'm unable to correctly build them. 

I followed the README file, build the GearVRf repo and tried to build GearVRf-Demos/gvr-complexscene with this result:
```
# ./gradlew assembleDebug
Incremental java compilation is an incubating feature.
:app:copyOculusSignature UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareBackendDebugLibrary UP-TO-DATE
:app:prepareFrameworkDebugLibrary UP-TO-DATE
:app:prepareGoogleVrBaseLibrary UP-TO-DATE
:app:prepareGoogleVrCommonLibrary UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:prePackageMarkerForDebug
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/oculus/systemutils/BuildConfig;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.843 secs
```

Is there some way how to fix this or can you help me figuring out what can cause this problem? I can post more information about my building environment if needed. 
Thank you, Michal :-)

**Comment by liaxim** [comment]
Most likely you still have VrApi.jar and SystemUtils.jar under the framework module (GearVRf/GVRf/Framework/framework/src/main/libs/). Please remove them from there, clean and build.

**Comment by rincewindcz** [comment]
Well, that helped! Now it builds successfully -- thank you, I was bit clueless about this one.

**Comment by amallo** [comment]
Hi, I have same issue, removed VrApi.jar and SystemUtils.jar under the framework module (GearVRf/GVRf/Framework/framework/src/main/libs/) and still same error

**Comment by liaxim** [comment]
@amallo Those jars must be picked up from someplace else. Try clean and rebuild first. If that doesn't help, you will have to examine the contents of the various aars your project depends on to find out where the extra VrApi and SystemUtils come from.

**Comment by amallo** [comment]
@liaxim  Thanks that what's I did, I removed SystemUtils.jar from (GearVRf/GVRf/Framework/framework/src/main/libs/)  was double somewhere, now it works !
