### ISSUE TITLE
Out of memory error in gvr-VRGallary while loading images

### ISSUE THREAD

**Issue by revinfopawan** [gearvrf/GearVRf-Demos#324]
Hello,

i am getting out of memory error in gvr-VRGallary app while loading  images . I add 
`dexOptions {
        javaMaxHeapSize "4g"
    }`
in gradle and
`android:largeHeap="true"`
in the manifest file  but still i am getting same error when trying to load no. of images and with high quality.
Thanks!

**Comment by revinfopawan** [comment]
Is there any other sample  code that i can use for this because i tried a lot to handle this  issue, i did googling but won't get solution.

**Comment by liaxim** [comment]
If what you are trying to load and keep in memory amounts to too much then either load less images and/or resize the images and/or use texture compression. Probably combination of all three. For texture compression see http://malideveloper.arm.com/resources/tools/mali-gpu-texture-compression-tool/.

It might be helpful if you could give us more details: like number of images, how many of them you want to be visible at the same time, image resolution and format.

**Comment by revinfopawan** [comment]
Because i am trying to load all images from gallery . We can't predict the number of images in the gallery because user can click more images

**Comment by liaxim** [comment]
@revinfopawan Hi, what do you think is possible for us to do to help you?

**Comment by revinfopawan** [comment]
Yes, May be. Because i won't get its solution , i am still doing googling to find out the solution.

**Comment by deepakrawat22** [comment]
@revinfopawan Could you please share more details regarding this issue, or if possible your source code. Thanks.
