### ISSUE TITLE
Combine samples into one

### ISSUE THREAD

**Issue by rahul27** [gearvrf/GearVRf-Demos#35]
Now that we can interact with a ListView (look at https://github.com/gearvrf/GearVRf-Demos/tree/master/events-sample). Would it be a good idea to combine some of the simple applications into one that can demo features based on ListView selection. 

Just like the api demo on android.

Let me know what you think?

**Comment by thomasflynn** [comment]
yep.  I started working on that on the plane.  I wanted to integrate it into the gvr-remote-scripting sample.  That way, in a talk, i can introduce scripting, then UI with Android FrameLayouts, using the list to select different 360 photo backgrounds.  Also, show how to play a 360 video from the script.  And if i can get it to work, show something with using a WebView as a UI as well.

**Comment by ragner** [comment]
@thomasflynn, It looks nice! 

@rahul27, I am trying to test events-sample with my Note4 but it is not updating the TextView after touch on the Buttons or select some item of the list. It is updating just after pressing the back button of the GearVR ... The motion events looks working well.

**Comment by rahul27** [comment]
@ragner - that's odd. I just tried it with my Note 4 (SM-N9100) and my Gear VR Innovator edition and it worked fine. 

Here are a few questions for you:

1. When you tap on the buttons/checkbox the TextView does not change? 
2. What happens with you use the volume up/down buttons, does that update the TextView?
3. When you tap anywhere on the layout do you see KEYCODE_BUTTON_1?

Also could you let me know the Note 4 version you are using also if your VR header is the innovator or the consumer one?

If we still get nowhere I might have you try a version with logs in them to help me debug the issue.

**Comment by rahul27** [comment]
If you have an S6 around could try it on there and let me know if you still see the problem. Thanks.

**Comment by ragner** [comment]
1. No, It does not change the TextView.
2. Yes, It does.
3. Yes, I do.

I am using the Note 4(SM-N910C, Android 5.1.1) and VR header Innovator.

I have tested with a S6 Edge and everything is working. 

 I will debug it today to send you more informations about this issue.

Thank you.

**Comment by ragner** [comment]
I did a factory reset on my Note 4 and now the sample is working :100:

**Comment by liaxim** [comment]
@rahul27 This doesn't seem to be happening. Should we close the issue? Or can you be more specific and suggest which samples should be combined? If we have something specific then it is more likely things will get done.

**Comment by rahul27** [comment]
I can close this, we could get back to it when the number of samples gets too big to maintain and test.
