### ISSUE TITLE
Can't create osig in China???

### ISSUE THREAD

**Issue by ja3son** [gearvrf/GearVRf-Demos#355]
I tried these website:
https://developer.oculus.com/osig/
https://dashboard.oculus.com/tools/osig-generator/ 
no one can visit.
how can i get the osig??
or
can i develop without the osig???

**Comment by ja3son** [comment]
anyone there????????

**Comment by dnvasilev** [comment]
ja3on,
Please describe what happens when you visit http://developer.oculus.com/
