### ISSUE TITLE
Manifest properties for Daydream

### ISSUE THREAD

**Issue by mkeblx** [gearvrf/GearVRf-Demos#358]
I believe some additional properties should be added to all demo manifests for Daydream (and Cardboard) support, would make a bit easier so wouldn't have to add oneself for.

```xml
<!-- Required to detect viewer insertion. -->
<!-- NOTE: could leave default commented out as only need for Daydream --> 
<uses-permission android:name="android.permission.NFC" />

<!-- Daydream, can't hurt, req=false -->
<!-- Indicates use of Android's VR-mode, available only on Android N+. -->
<uses-feature android:name="android.software.vr.mode" android:required="false" />
<!-- Indicates use of VR features that are available only on Daydream-ready devices. -->
<uses-feature android:name="android.hardware.vr.high_performance" android:required="false" />

<!-- For listing in Cardboard app, Daydream home -->
<intent-filter>
  <category android:name="com.google.intent.category.CARDBOARD" />
  <category android:name="com.google.intent.category.DAYDREAM" />
</intent-filter>

<!-- ? -->
<activity
    android:enableVrMode="@string/gvr_vr_mode_component">
```

@thomasflynn mentioned one option might be to conditionally/additionally modify manifest via gradle.
https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/backend_daydream/build.gradle

See:
https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/src/main/AndroidManifest.xml

**Comment by thomasflynn** [comment]
I was saying I thought there was something one already either in the manifest in the daydream backend or the daydream backend gradle file.  I'm not seeing it now, but i could swear i remember seeing a commit along those lines.

**Comment by liaxim** [comment]
See https://github.com/Samsung/GearVRf/pull/916. I don't know whether the entries for the activity (intent-filter and the enableVrMode attribute) can be included since the activity is unique per app.

**Comment by mkeblx** [comment]
Does the backend_daydream manifest in that GearVRf PR effect the built manifests in -demos? Otherwise should be modified too I think. 

If add DAYDREAM intent filter perhaps a little premature & can wait as would need to handle input accordingly in app, easier with future release:
https://github.com/googlevr/gvr-android-sdk/issues/286
https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/Constants

(Also, have a Pixel if desired for testing.)

**Comment by liaxim** [comment]
Yes, the manifests get merged by the toolchain so whatever is in the Daydream manifest gets its way into the final app's manifest (build-time).

**Comment by liaxim** [comment]
I believe we did what we can. Planning to close unless there are some suggestions what more we could do.

**Comment by rahul27** [comment]
The enable vr mode can be set programmatically using the following command:
````
    // This configuration won't be required for normal GVR apps. However, since this sample doesn't
    // use GvrView, it needs pretend to be a VR app in order to receive controller events. The
    // Activity.setVrModeEnabled is only enabled on in N, so this is an GVR-internal utility method
    // to configure the app via reflection.
    //
    // If this sample is compiled with the N SDK, Activity.setVrModeEnabled can be called directly.
    AndroidCompat.setVrModeEnabled(this, true);
````

As stated in the comments (taken from a daydream sample) the flag is not required if we use GvrView, which we do in our DayDream backend. The flag is therefore enabled by default. 

Regarding the intent filter, for now the GVRf apps seem to launch fine. I guess adding the filters would be a hard requirement for publishing Daydream apps(similar to the Manifest changes required for Oculus). 

That being said if things change in the future we could make the required changes. For now it looks like we have the necessary changes in place.
