### ISSUE TITLE
moving old demos to another directory

### ISSUE THREAD

**Issue by thomasflynn** [gearvrf/GearVRf-Demos#362]
We have quite a few demos now-a-days and the signal-to-noise ratio of good examples showing the current way of loading models and picking and etc. vs the older, more difficult way of doing things should be improved.  I'd like to move a number of samples that fall into the latter category into a subdirectory.  Maybe we could call it "old/" or something.

Here's a list of demos I think we could just move to that subdirectory:
gvr-cockpit
gvr-litshader
gvr-nonglthreadupdate
gvr-panorama
gvr-simplegallery
gvr-opacityanigallery
gvr-jassimp
gvr-exposeapi
gvr-collision
gvr-pickandmove
gvr-sample
gvr-screenshot
gvr-sixaxissensor
gvr-testcube
gvr-textviewsample
gvr-modelviewer

There are a few of those that do show how to use some parts of the framework that aren't covered elsewhere.  I think maybe we should update some of the rest of our demos to show those features. 

The following two were meant as tests and could probably move to the new GearVRf-Tests repo:
gvr-lodtest
gvr-transparencytest

And finally, the following list of demos should be updated to use our latest apis and be a bit more polished:
gvr-immersivepedia
gvr-controls
gvr-keyboard
gvr-bullet
gvr-eyepicking
gvr-vuforia
gvr-widgetviewer

Does anyone else have suggestions of apps to move or keep?

**Comment by liaxim** [comment]
gvr-scene-editor - to the main repo since it is a tool
gvr-testmodels - to the tests repo

**Comment by rahul27** [comment]
gvr-inputsample can be moved to the old subdirectory. It is outdated and is replaced by gvr-3dcursor.

**Comment by liaxim** [comment]
Should the old demos be built by the automated build?

**Comment by liaxim** [comment]
Pull request for moving apps under the "old" folder: https://github.com/gearvrf/GearVRf-Demos/pull/364

**Comment by liaxim** [comment]
Pull requests for the gvr-scene-editor
- delete from the demos repo: https://github.com/gearvrf/GearVRf-Demos/pull/365
- copy to the main repo: https://github.com/Samsung/GearVRf/pull/931

**Comment by liaxim** [comment]
Test apps pull requests (gvr-lodtest, gvr-testmodels and gvr-transparencytest)

- remove from the demos: repo https://github.com/gearvrf/GearVRf-Demos/pull/366
- add to the tests repo: https://github.com/gearvrf/GearVRf-Tests/pull/32

**Comment by liaxim** [comment]
Should the apps needing polishing be updated for this release?

**Comment by thomasflynn** [comment]
no, the apps don't need polishing before the release.  they'll each probably require quite a bit of work.
the old demos don't need to be built by the automated build.
i think i missed something w.r.t. the scene-editor.  why are we moving that out of demos and into the main repo?

**Comment by liaxim** [comment]
The scene-editor is a tool and maybe doesn't belong with the rest of the demos?

**Comment by liaxim** [comment]
Created https://github.com/gearvrf/GearVRf-Demos/issues/370 to record the list of apps we need to update. I plan to close this ticket if there are no other action items associated with it.

**Comment by deepakrawat22** [comment]
gvr-complexscene can also be moved to old/ directory or test. Its used for test purpose only.

**Comment by thomasflynn** [comment]
this was done a long time ago
