### ISSUE TITLE
List of apps that need updates

### ISSUE THREAD

**Issue by liaxim** [gearvrf/GearVRf-Demos#370]
Per Tom:

And finally, the following list of demos should be updated to use our latest apis and be a bit more polished:
gvr-immersivepedia
gvr-controls
gvr-keyboard
gvr-bullet
gvr-eyepicking
gvr-vuforia
gvr-widgetviewer

**Comment by mwitchwilliams** [comment]
I believe ModelViewer2 is in need of an update.
It imports org.gearvrf.widgetplugin.GVRWidgetPlugin which I don't believe there is a widgetplugin directory in org.gearvrf.

**Comment by liaxim** [comment]
@mwitchwilliams It is an extension; see GearVRf/GVRf/Extensions/WidgetPlugin.

**Comment by liaxim** [comment]
At least the API usage has been corrected. Planning to close in few days.
