### ISSUE TITLE
Conclusion..! Is there any way in GeerVR API to render youtube videos  ??

### ISSUE THREAD

**Issue by Maqsood007** [gearvrf/GearVRf-Demos#379]
Sir i want to conclude that is there any way exist so i can play youtube videos in GeerVR application. any way to use webview or any other 3rd part webAPI ??

**Comment by liaxim** [comment]
Do you happen to have a regular Android sample app that has the WebView rendered to a SurfaceTexture that shows youtube videos playing? If you can show us a sample that does work that would help. Based on the investigation the team did it is just not possible (see http://stackoverflow.com/questions/19273437/android-draw-youtube-video-on-surfacetexture for example). There is a separate youtube API (https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/package-summary) but it is very restrictive - you need to derive your Activity from YouTubeBaseActivity.

**Comment by liaxim** [comment]
@Maqsood007 Do you have anything for us? Planning to close this ticket soon otherwise.

**Comment by shaishav-mtech** [comment]
I have got it working! check [this](https://github.com/Samsung/GearVRf/issues/1033#issuecomment-278244683)
