### ISSUE TITLE
Could not find method android() for arguments 

### ISSUE THREAD

**Issue by qiqi520** [gearvrf/GearVRf-Demos#391]
How Could I fix this.

Error:(16, 0) Could not find method android() for arguments [build_6l8lc8ex9mzio8cerf4m23bg$_run_closure2@15d382d3] on root project 'gvr-simplesample' of type org.gradle.api.Project.
<a href="openFile:F:\GVR\GearVRf-Demos-master\gvr-simplesample\build.gradle">Open File</a>

**Comment by liaxim** [comment]
Hi. Which version of the framework are you trying to use? Which version of Android Studio? Are you trying to import in Android Studio from the GearVRf-Demos/gvr-simplesample/ directory?

**Comment by liaxim** [comment]
@qiqi520 Assuming you managed to resolve your problem. Let us know if that is not the case. Otherwise I will close this issue soon.
