### ISSUE TITLE
gvr-video for stereo videos

### ISSUE THREAD

**Issue by sam16222** [gearvrf/GearVRf-Demos#404]
I tried using the sample app gvr-video for playing 3D(stereo) videos. On changing the screen object to GVRVideoType.HORIZONTAL_STEREO, I am able to render the video but the shaders are not rendering the left side of the theatre. Can you tell me what changes are required?

**Comment by liaxim** [comment]
I just tried and it all seems to work correctly to me. For both eyes there is nothing missing from the theater. Maybe you could attach a screenshot?

**Comment by sam16222** [comment]
![screenshot_20170217-094334](https://cloud.githubusercontent.com/assets/6275033/23059143/09804fb2-f51e-11e6-8586-e3753cfc219e.png)

**Comment by sam16222** [comment]
As you can see, the left side isn't illuminated. All that I have done is set the screen to GVRVideoType.HORIZONTAL_STEREO. Let me know if that's a bug or do I need to make any other changes.

**Comment by liaxim** [comment]
It is likely a bug in the gvr-video sample itself. Do you observe the same effect when you are using the default video that comes with the sample and use HORIZONTAL_STEREO (regardless the fact the video is not)?

**Comment by sam16222** [comment]
No I don't. That's what I wanted to ask. How does the shader work in this case, and is there something to be changed for the shader?

**Comment by liaxim** [comment]
The likelihood is that it is the shader but unless we can reproduce, it could take a while. I found a random stereo video and it worked for me. Do you have this problem with all stereo videos? What phone are you using and which Android version?

**Comment by liaxim** [comment]
@sam16222 Can you suggest a video that shows the problem?

**Comment by liaxim** [comment]
Planning to close the issue unless we get more information how to reproduce. I couldn't with the stereo videos I found.
