### ISSUE TITLE
How can we make api calls to server to fetch video files? 

### ISSUE THREAD

**Issue by pre2612** [gearvrf/GearVRf-Demos#405]
Trying to make a api call to fetch video files from server in GVRACTIVITY using ASYNC task. Not working any help would be appreciated!

Thanks so mucj

**Comment by liaxim** [comment]
@pre2612 We will need more details. Like are you seeing exceptions? Can you share code snippets? Thanks.

**Comment by pre2612** [comment]
Thanks so much for replying back. Please find below my code. I am trying to get mp4 file which is variable named "lectures" in code. How can that be passed to Videomain and wait till we get mp4 file from asyncTask.



public class VideoActivity extends GVRActivity {
private VideoMain mMain = null;
private long lastDownTime;
private ProgressDialog progress;
String session;

@Override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
mMain = new VideoMain(this);
new PostClass().execute();
//addVr Content Here
setMain(mMain, "gvr.xml");
}

@Override
protected void onPause() {
super.onPause();
mMain.onPause();
}

@Override
public boolean onTouchEvent(MotionEvent event) {
super.onTouchEvent(event);
mMain.onTouch();
if (event.getActionMasked() == MotionEvent.ACTION_DOWN) {
lastDownTime = event.getDownTime();
}

if (event.getActionMasked() == MotionEvent.ACTION_UP) {
if (event.getEventTime() - lastDownTime < 200) {
mMain.onTap();
}
}
return true;
}


//Async task


private class PostClass extends AsyncTask<String, Void, Void> {


@Override
protected Void doInBackground(String... params) {
try {
URL url = new URL("");

HttpURLConnection connection = (HttpURLConnection)url.openConnection();
String urlParameters = "";
connection.setRequestMethod("POST");
connection.setRequestProperty("USER-AGENT", "Mozilla/5.0");
connection.setRequestProperty("ACCEPT-LANGUAGE", "en-US,en;0.5");
connection.setDoOutput(true);
DataOutputStream dStream = new DataOutputStream(connection.getOutputStream());
dStream.writeBytes(urlParameters);
dStream.flush();
dStream.close();
int responseCode = connection.getResponseCode();

System.out.println("\nSending 'POST' request to URL : " + url);
System.out.println("Post parameters : " + urlParameters);
System.out.println("Response Code : " + responseCode);

final StringBuilder output = new StringBuilder("Request URL " + url);
output.append(System.getProperty("line.separator") + "Request Parameters " + urlParameters);
output.append(System.getProperty("line.separator")  + "Response Code " + responseCode);
output.append(System.getProperty("line.separator")  + "Type " + "POST");
BufferedReader br = new BufferedReader(new InputStreamReader(connection.getInputStream()));


StringBuffer res = new StringBuffer();
String line;
while ((line = br.readLine()) != null) {
res.append(line);
}
br.close();

try{
JSONObject jsonObj = new JSONObject(res.toString());
session = jsonObj.getString("SessionID");
}catch (JSONException e) {

VideoActivity.this.runOnUiThread(new Runnable() {

@Override
public void run() {
new GetClass().execute();
}
});


} catch (MalformedURLException e) {
// TODO Auto-generated catch block
e.printStackTrace();
} catch (IOException e) {
// TODO Auto-generated catch block
e.printStackTrace();
}
return null;
}

}

private class GetClass extends AsyncTask<String, Void, Void> {


@Override
protected Void doInBackground(String... params) {
try {
URL url = new URL("");

HttpURLConnection connection = (HttpURLConnection)url.openConnection();
connection.setRequestMethod("GET");
connection.setRequestProperty("USER-AGENT", "Mozilla/5.0");
connection.setRequestProperty("ACCEPT-LANGUAGE", "en-US,en;0.5");
connection.setRequestProperty("SessionID", session);

int responseCode = connection.getResponseCode();

System.out.println("\nSending 'GET' request to URL : " + url);
System.out.println("Response Code : " + responseCode);

final StringBuilder output = new StringBuilder("Request URL " + url);
//output.append(System.getProperty("line.separator") + "Request Parameters " + urlParameters);
output.append(System.getProperty("line.separator")  + "Response Code " + responseCode);
output.append(System.getProperty("line.separator")  + "Type " + "GET");
BufferedReader br = new BufferedReader(new InputStreamReader(connection.getInputStream()));
StringBuffer res = new StringBuffer();
String line;
while ((line = br.readLine()) != null) {
res.append(line);
}
br.close();

try{
JSONObject jsonObj = new JSONObject(res.toString());
JSONArray lectures = jsonObj.getJSONArray("Lectures");
}catch (JSONException e) {
}




} catch (MalformedURLException e) {
// TODO Auto-generated catch block
e.printStackTrace();
} catch (IOException e) {
// TODO Auto-generated catch block
e.printStackTrace();
}
return null;
}

protected void onPostExecute() {
progress.dismiss();
}


}

//End asyn task


}

Appreciate your help!

**Comment by thomasflynn** [comment]
Hi there.  This seems to be a bit out of scope of GearVRf and seems to be more of a general Java question.  However, I asked someone to take a quick look at it anyway.  Here is his response.  Hope it helps:

@pre2612

Thanks for posting the code. So far you already have a JSONArray in variable 'lectures' which presumably contains a list of URLs pointing to the mp4 videos.

At this moment if you want to notify VideoMain that these videos are being downloaded you can throw a runnable to notify VideoMain like this -

                VideoActivity.this.runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                                mMain.onStartDownloadingMp4Videos(lectures);
                                }
                }

This notification allows VideoMain to start tracking the video downloading progress. It may show some UI so the user gets informed.

Inside GetClass, the real downloading starts right after the above Runnable is scheduled. At the end of the downloading of each mp4 pointed to by the JSONObject
contained in lectures, a MP4 file is generated and represented as a File object 'mp4file'. At this time we can notfiy VideoMain the result by calling -
                VideoActivity.this.runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                                mMain.onMp4DownloadFinished(lectures, mp4Index, mp4file);
                                }
                }
where mp4Index is the integer index into the JSONArray. When mp4file is null, VideoMain can assume the download failed.


There are some articles online regarding downloading mp4 videos, such as
                http://stackoverflow.com/questions/14951513/how-to-update-progressbar-when-download-mp4-video
                http://stackoverflow.com/questions/15407900/android-phone-crashes-on-downloading-videomp4-file

**Comment by liaxim** [comment]
@pre2612 Was this helpful? Planning to close the issue soon.

**Comment by liaxim** [comment]
@pre2612 Assuming it is all good. You can always reopen the issue if that is not the case.
