### ISSUE TITLE
failed to resolve daydream 1.1.1 snapshot

### ISSUE THREAD

**Issue by tjoshi03** [gearvrf/GearVRf-Demos#411]
failed to resolve org.gearvrf:backed_daydream:3.1.1-SNAPSHOT

**Comment by liaxim** [comment]
@tjoshi03 The issue has been fixed. Please update your repo and try again.

**Comment by tjoshi03** [comment]
sorry to ask but how to update repo

**Comment by liaxim** [comment]
If you are using git then you can issue ``git pull --rebase``. If you have downloaded a zip archive please download it again.

**Comment by liaxim** [comment]
@tjoshi03 Are you still having problems?

**Comment by liaxim** [comment]
Assuming it is all good.

**Comment by tjoshi03** [comment]
thanks for the help dev my problem is solved
