### ISSUE TITLE
Demo APK build fails with DexException

### ISSUE THREAD

**Issue by johncromie** [gearvrf/GearVRf-Demos#412]
I can run and debug the GearVRf demo apps fine on the device but when I go to build an APK, the build fails with a DexException. This seems to have appeared after upgrading to Android Studio 2.3.

Executing tasks: [:gvr-3dcursor:assembleRelease]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/john/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at XmlValidator.apply(/Users/john/xxxxxx/GearVRf/GearVRf-Demos/gvr-3dcursor/app/build.gradle:70)
Incremental java compilation is an incubating feature.
:gvr-3dcursor:copyOculusSignature UP-TO-DATE
:gvr-3dcursor:validateXml
Validating settings.xml file
:gvr-3dcursor:preBuild
:gvr-3dcursor:preReleaseBuild
:gvr-3dcursor:checkReleaseManifest
:gvr-3dcursor:preDebugBuild
:gvr-3dcursor:prepareComGoogleVrSdkBase1100Library
:gvr-3dcursor:prepareComGoogleVrSdkCommon1100Library
:gvr-3dcursor:prepareOrgGearvrf3DCursorLibrary311Library
:gvr-3dcursor:prepareOrgGearvrfBackend_daydream311Library
:gvr-3dcursor:prepareOrgGearvrfBackend_oculus311Library
:gvr-3dcursor:prepareOrgGearvrfFramework311Library
:gvr-3dcursor:prepareOrgGearvrfGearWearIoDevice311Library
:gvr-3dcursor:prepareOrgGearvrfGearwearlibrary311Library
:gvr-3dcursor:prepareOrgJomlJomlAndroid191SNAPSHOTLibrary UP-TO-DATE
:gvr-3dcursor:prepareReleaseDependencies
:gvr-3dcursor:compileReleaseAidl
:gvr-3dcursor:compileReleaseRenderscript
:gvr-3dcursor:generateReleaseBuildConfig
:gvr-3dcursor:generateReleaseResValues
:gvr-3dcursor:generateReleaseResources
:gvr-3dcursor:mergeReleaseResources
:gvr-3dcursor:processReleaseManifest
:gvr-3dcursor:processReleaseResources
:gvr-3dcursor:generateReleaseSources
:gvr-3dcursor:incrementalReleaseJavaCompilationSafeguard
:gvr-3dcursor:javaPreCompileRelease
:gvr-3dcursor:compileReleaseJavaWithJavac
:gvr-3dcursor:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: /Users/john/xxxxxx/GearVRf/GearVRf-Demos/gvr-3dcursor/app/src/main/java/org/gearvrf/io/cursor/CursorMain.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:gvr-3dcursor:compileReleaseNdk UP-TO-DATE
:gvr-3dcursor:compileReleaseSources
:gvr-3dcursor:mergeReleaseShaders
:gvr-3dcursor:compileReleaseShaders
:gvr-3dcursor:generateReleaseAssets
:gvr-3dcursor:mergeReleaseAssets
:gvr-3dcursor:transformClassesWithDexForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gvr-3dcursor:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/joml/AxisAngle4d;

**Comment by liaxim** [comment]
@johncromie I built a release and debug apks for the gvr-3dcursor app without issue. Could you please completely clean your GearVRf-Demos tree via ``git clean -fdx``, try again and let us know what happens?

**Comment by johncromie** [comment]
Thanks @liaxim. So I cloned a fresh copy of GearVRf-Demos master and that built fine including building an APK. Further investigation revealed that common.gradle in master is more recent than the version I was using from release_v3.1.1. Replacing common.gradle with that from master, then resyncing, cleaning and building fixed the problem.

It looks like common.gradle in release_v3.1 has been updated more recently, while that in release_v3.1.1 is older. I assumed release 3.1.1 superseded 3.1.

**Comment by liaxim** [comment]
The release_v3.1.1 in the Demos repo was a staging branch. In hindsight we didn't pick a good name for it. I updated the branch so it is now in the expected state and to have consistently named branches across the repos. Thanks for your feedback.

**Comment by liaxim** [comment]
I believe we addressed the issue. Let us know if you think otherwise.
