### ISSUE TITLE
360 rotation scrolling of menu/ Like samsung VR home page how can it be achieved?

### ISSUE THREAD

**Issue by pre2612** [gearvrf/GearVRf-Demos#429]
Right now I have a android ListView instead of that want to use 360 scrolling Menu as Samsung VR home page. How can it be achieved? is there any sample which shows that?

**Comment by liaxim** [comment]
@pre2612 The closest thing we have is the https://github.com/gearvrf/GearVRf-Demos/tree/master/old/gvr-simplegallery sample. Bear in mind it is nowhere as slick and not componentized but should give you an idea.

**Comment by liaxim** [comment]
@pre2612 Was that any help?

**Comment by liaxim** [comment]
@pre2612 Let us know if you have further questions.
