### ISSUE TITLE
camera2renderscript: non fatal errors

### ISSUE THREAD

**Issue by Joshf17000548** [gearvrf/GearVRf-Demos#433]
When running camera2renderscript "out the box", it gives the following non fatal errors in logcat:

E/RenderScript_jni: non fatal RS error, Error sending USAGE_IO surface.
E/RenderScript_jni: non fatal RS error, Error creating buffer.
E/RenderScript_jni: non fatal RS error, Error receiving USAGE_IO buffer.

Are these errors something to do with mInputAllocation.ioReceive(); and mOutputAllocation.ioSend();? Could it possibly be, because the renderscript can't keep up with the camera?

Think I should mention that I'm running the app on a Samsung Galaxy s7 Edge.

**Comment by liaxim** [comment]
Hi. I have no idea and I don't think we have a RS expert on the team. There are no hints what these errors might mean.

Does the app work correctly for you? There should be two quads. The top one should be black and white and the one at the bottom in color. What is the model number of your device (``adb shell getprop|grep product.model``)? And the Android version (``adb shell getprop|grep build.version``)?

**Comment by Joshf17000548** [comment]
Yes the app works perfectly. Model number: SM-G935F. Android Version: 6.0.1. Do these errors appear on different phones? Maybe something with the YUV conversion if it doesn't.

**Comment by liaxim** [comment]
Tried couple of phones that perform the YUV conversion. Nothing in my logs.

**Comment by liaxim** [comment]
@Joshf17000548 Closing for now. Let us know if you have any ideas.
