### ISSUE TITLE
Exoplayer2

### ISSUE THREAD

**Issue by AntonAFA** [gearvrf/GearVRf-Demos#445]
Do you attend to support exoplayer2?

**Comment by bohuang3d** [comment]
@AntonAFA not sure there is any roadmap for that. What's the feature you need that's not in the Android Media player or Exoplayer 1?

**Comment by AntonAFA** [comment]
The only reason i need is that i am working with exoplayer2 now. Also, if i understand correctly Exoplayer2 is the version they are improving and developing now. So the exoplayer1 will be outdated soon.

**Comment by liaxim** [comment]
@AntonAFA In your experience are the API changes in v2 major? v2 will be the go to version for Android O.

**Comment by liaxim** [comment]
Nothing prevents it to my knowledge. But it has to be tried to determine how different the ExoPlayer2 API is. You never know.. For example, the Android YouTube API requires you to derive from an activity of its own which means we can't use it.

**Comment by liaxim** [comment]
@AntonAFA Did you manage to switch to ExoPlayer2?

**Comment by Armillary** [comment]
I've tried to get exoplayer2 working with some issue. Its very possible that I'm making a mistake that is not related to GearVRf however at present the player will open without logging any errors but display a black screen for a local HLS stream. The only warnings I'm getting are about unsupported mime types.

**Comment by bohuang3d** [comment]
@Armillary 

That could be a video codec issue or something inherent with exoplayer2.

Can you play on the same phone with a different player?

**Comment by liaxim** [comment]
@Armillary If you can share with us a sample project we might be able to help you quicker.

**Comment by Armillary** [comment]
Ive left the office for the week, ill post full details on Monday when I'm back at my work computer.

**Comment by bohuang3d** [comment]
Looks like the same or similar issue to 
https://github.com/googlevr/gvr-android-sdk/issues/75

**Comment by liaxim** [comment]
@Armillary At the end of the setSurface method you need to make a ``player.setVideoSurface(surface);`` call. In your code you never pass the surface to ExoPlayer.

**Comment by Armillary** [comment]
@liaxim That solved my problem, I apologize for the oversight. I'm still fairly new working with exoplayer. Once I've cleaned up my code I'll post a sample so anyone else looking to work with Exoplayer2 in GearVRf will have a reference.

**Comment by liaxim** [comment]
@Armillary Thanks for the effort. Can we close the issue now?

**Comment by Armillary** [comment]
That seems to be fine at this point.
