### ISSUE TITLE
Could not find framework.jar

### ISSUE THREAD

**Issue by polopolo234** [gearvrf/GearVRf-Demos#449]
Hi,

after loading GearVRf-Demos example in Android Studio I get the following Error message:

`Error:Couldnot find framework.jar (org.gearvrf:framework:3.2.1-SNAPSHOT).
Searched in the following locations:
https://oss.sonatype.org/content/repositories/snapshots/org/gearvrf/framework/3.2.1-SNAPSHOT/framework-3.2.1-20170505.214953-3.jar`

where can I change the path to that folder ?

for helping thank you very much.

**Comment by liaxim** [comment]
Hi. Thanks for letting us know. Not sure where this is coming from. While we investigate you could just switch to the 3.2 branch that will use a stable release of the framework: ``git clone -b release_v3.2 git@github.com:gearvrf/GearVRf-Demos.git``.

**Comment by liaxim** [comment]
Snapshots have been updated and the problem is gone. Please run gradle with the ``--refresh-dependencies`` parameter once.
