### ISSUE TITLE
360 stereo photosphere

### ISSUE THREAD

**Issue by Cyganieszka** [gearvrf/GearVRf-Demos#457]
gvr-360photo example is really straightforward, but it only displays mono panorama. I can't find any clue how to display stereo panorama. I tried to use top/bottom double equrectangular photosphere with this example, but it's displayed just as two images on sphere. 

I've found unity examples for that, but not even one GearVR example. Any hint how to achieve stereo panorama/ stereo cube map will be highly appreciated.

**Comment by liaxim** [comment]
For top/bottom you should use the correct shader type:
```sphereObject.getRenderData().getMaterial().setShaderType(GVRMaterial.GVRShaderType.UnlitVerticalStereo.ID);```

**Comment by Cyganieszka** [comment]
Thanks! It worked, but it also says that this method is deprecated.

`'setShaderType(org.gearvrf.GVRShaderId)' is deprecated `

**Comment by liaxim** [comment]
Do not worry for the deprecation. It was a bit premature since we do not provide non-deprecated alternative for this.
