### ISSUE TITLE
360 Video

### ISSUE THREAD

**Issue by parth727** [gearvrf/GearVRf-Demos#458]
I am facing issue with 360Video.
As and When I am trying to load video by default it will move 90 degree right.
I can not able to load video straight.

**Comment by Cyganieszka** [comment]
Maybe it's not a solution, but at least workaround. 
You can turn GVRVideoSceneObject 90 deg to the right:

`video.getTransform().setRotation(0.7071f,0,-0.7071f,0);`

**Comment by parth727** [comment]
@Cyganieszka  Thank you

Its working...

**Comment by parth727** [comment]
Can I get device x position as I want to check whether the device is moving left side or right side.??

**Comment by liaxim** [comment]
@parth727 May or may not be relevant to what you do but fyi: there is GVRCameraRig.reset that will re-center your view.

**Comment by liaxim** [comment]
@parth727 Do you want to tell whether the user rotates his/her head left/right or moves to the left or right (as in translation)?

Rotation is possible: one way would be storing and comparing old vs current GVRMainCameraRig.getHeadTransform().getRotationYaw(). Making it reliable probably requires some filtering.

Position not so much. I guess the accelerometer with some heuristics could kind of work.

**Comment by parth727** [comment]
@liaxim  Thank you for quick reply.
I want translation, I have tried accelerometer options with multiple possibilities but couldn't achieve my requirement.
I want result in left side 90 degree and right side 90 degree

**Comment by parth727** [comment]
How can i show text on 360Video??
I have tried below code but it does not work.

 textView = new GVRTextView(minimal360VideoActivity, 150,
                150);
        textView.setTextSize(220);
        textView.setTextColor(ContextCompat.getColor(minimal360VideoActivity, R.color.colorAccent));
        textView.setTypeface(Typeface.DEFAULT_BOLD);
        textView.setText("RIght");
        textView.setBackgroundColor(Color.TRANSPARENT);

  GVRViewSceneObject text = new GVRViewSceneObject(gvrContext,textView,50,50);
        scene.addSceneObject(text);

**Comment by parth727** [comment]
Can we Print toast or show dialog in GVRActivity?

**Comment by thomasflynn** [comment]
we do have these:

GVRContext.showToast(final String message)
GVRContext.showToast(final String message, float duration)

**Comment by liaxim** [comment]
@parth727 Regarding your showing text question.. Please let us know at what position you are putting your ``text`` scene object. Also note that you must create the ``GVRTextView`` instance on the Android main thread since it is an Android view.

**Comment by liaxim** [comment]
@parth727 Assuming it is all good. Planning to close this issue in a day or two. You can always re-open if you have something for us.
