### ISSUE TITLE
grv-360video sample and samsung VR video player difference. 

### ISSUE THREAD

**Issue by Cyganieszka** [gearvrf/GearVRf-Demos#460]
Problem: 360 3D video is displayed differently in SamsungVR and grv-360video sample. 

In grv-360video sample app, after changing GVRVideoType.MONO to GVRVideoType.VERTICAL_STEREO, and replacing video to stereographic one, you are able to display 3D 360 video. But it looks slightly different than on samsung's player. To spot the difference, I've made a screenshots in "almost" same time, and looking in "almost" same point. On grv-360video app, both images were moved to center of screen (views boundaries are exactly the same position, just their content is moved), like the views were a little cross-eyed. It's not something destroying look and feel, but I need to make it "just like on other vr player".

It's difficult to describe, I will find some video which is publicly available and create screenshots to show what I mean. 

By this time, maybe someone knows what I'm doing wrong. Are there any additional steps needed to display stereoscopic 3d video?

**Comment by thomasflynn** [comment]
the steps you've taken sound correct.  screenshots might be helpful.  a video would definitely be helpful.  

the only thing i could guess from your description is maybe the sphere is too close?  therefore the eyes are converging at a point that is really close as opposed to further away (and not cross-eyed)?  We upped the size of the sphere we use in gvr-360video sometime in the last month or two (actually it was a bug we fixed in the sample..the code for scaling up the sphere was incorrect).  Maybe you want to double check that code in master?  Maybe increase the size of the sphere further?

see what you can do to get something for us to look at.  it's going to be difficult to guess without some visual reference.

**Comment by thomasflynn** [comment]
Ok, I managed to get my hands on a top/bottom stereo 360 video.  It's also not public.  Was able to play it in both gvr-360video (after modifying it to read the file from sdcard and to use the VERTICAL_STEREO shader) and the Samsung VR player.  I also took some screenshots (via adb shell screencap).  As you mentioned, it is difficult to get the same exact camera angle, but i took shots at 'almost' the same time and 'almost' the same spot.   

I took the images and put them into gimp and measured the distances between key pixels in the left and right eyes (key features of the main character that was moving in the video).  and the distances were either exactly the same or a single pixel off (probably due me being off when selecting which pixels to compare).  All screenshots were taken on a GS8+.  Perhaps the video I have is not a good candidate for showing the problem.

If you find something you can share with us, let us know.  And you don't have to share if via github.  You can email me at tom.flynn@samsung.com and let me know how to retrieve the file.

**Comment by thomasflynn** [comment]
you can perhaps try playing with the IPD.  we don't have a great way of dynamically changing it at runtime (was meant as more of a startup configuration thing), but it can be done.  What you can do is get a handle to the GVRCameraRig, then get a handle to the left and right cameras.  Then call the setCameraSeparationDistance() method (default is 0.062) and then call attachLeftCamera(), attachRightCamera().

with that you can maybe adjust it at runtime while you're looking at the video and see if there is a value that helps.

**Comment by bohuang3d** [comment]
@Cyganieszka

Can you try with GS8+ as @thomasflynn did? Just in case device screen sizes or potential dynamic screen scalings cause differences

**Comment by Cyganieszka** [comment]
Sorry I'm replying so late, I had too many other things to do. I've tested @thomasflynn solution, and changing IPD worked. To achieve the same result as in SamsungVR player, I had to set camera separation distance to 0. For me, it's not a noticeable difference, but my perfectionist customer is happy now. 

@bohuang3d I have only SG6.

**Comment by liaxim** [comment]
@Cyganieszka Is it all good now? Can we close the issue?

**Comment by liaxim** [comment]
@Cyganieszka Assuming it all worked out. You can always reopen the issue if you have updates for us. Thanks.
