### ISSUE TITLE
360 Degree Play's from a different angle

### ISSUE THREAD

**Issue by Malikkhoja** [gearvrf/GearVRf-Demos#484]
The gvr-360 degree video starts playing from a different angle. It doesn't play the video from the center like the other app does.

Can anyone help to solve this issue?

Thanks

**Comment by bohuang3d** [comment]
@Malikkhoja

I don't know what you mean. I launched the 360video app several times with GearVR facing different directions. Each time I see the karate dojo's circular window at the start of the scene with the guy appearing from the right.

**Comment by liaxim** [comment]
@Malikkhoja Any chance you could share a screenshot of what you mean?

**Comment by Malikkhoja** [comment]
@bohuang3d ,@liaxim  

Thanks for the reply.

I am working on a simple Native Android 360 degree app and I am new to Gear VRD Development.

The first screen is a splash screen where a logo appears but its not always where the user is looking. Its placed randomly every time.

My Code for the splash is 

  splashSceneObject = new GVRSceneObject(mGvrContext,
                new FutureWrapper<GVRMesh>(mGvrContext.createQuad(0.7f, 0.5f)),
                mGvrContext.loadFutureTexture(new GVRAndroidResource(mGvrContext, R.raw.logo)));
                   splashSceneObject.getTransform().setPositionX(0.0f);
               splashSceneObject.getTransform().setPositionY(0.0f);
               splashSceneObject.getTransform().setPositionZ(DEPTH);
        mainScene.addSceneObject(splashSceneObject);

I am unable to get the head tracking position which we could get in Unity. Can you please help me

Thanks in advance.

**Comment by bohuang3d** [comment]
@Malikkhoja

Seems you are placing the object at (0,0,DEPTH).

Can you provide how you are setting up the camera as well? 

Also, you mean the 'head tracking orientation' right? GearVR doesn't track positions. 

The GVRCameraRig class can help you get orientation.
```
GVRCameraRig myCameraRig = myScene.getMainCameraRig();
GVRTransform myTfm = myCameraRig.getTransform();
```

**Comment by liaxim** [comment]
@Malikkhoja Do experience this problem with any of our demo apps and its splash screen? What device and Android version are you using? Do you use developer mode (https://developer.oculus.com/documentation/mobilesdk/1.0.3/concepts/mobile-troublesh-device-run-app-outside/) ?

**Comment by liaxim** [comment]
@Malikkhoja Assuming it is all good. Will close in few days if there is no response from you.
