### ISSUE TITLE
How to view GIF on Gear VR?

### ISSUE THREAD

**Issue by zhangweizhe** [gearvrf/GearVRf-Demos#485]
How to view GIF on Gear VR? I can not find a demo about this

**Comment by liaxim** [comment]
@zhangweizhe We don't have anything for GIF's. Are you looking into animated GIFs?

There are various libraries that handle GIFs you could use. For example https://gist.github.com/devunwired/4479231. Then you will need to feed Android bitmaps into our GVRBitmapTexture.

**Comment by bohuang3d** [comment]
@zhangweizhe 

Another way is to convert your gif to a video. Then use GVRF's video player

**Comment by zhangweizhe** [comment]
@liaxim   I try to render a picture with bitmap using the following code

Bitmap bitmap = BitmapFactory.decodeResource(getGVRContext().getActivity().getResources(), R.drawable.champion);
        mBitmapTexture = new GVRBitmapTexture(gvrContext, bitmap);
        mGVRSceneObject = new GVRSceneObject(gvrContext, 3, 3, mBitmapTexture);
        GVRMaterial material = new GVRMaterial(gvrContext);
        mGVRSceneObject.getRenderData().setMaterial(material);
        mGVRSceneObject.getTransform().setPosition(0,0,-3);
        mGVRScene.addSceneObject(mGVRSceneObject);

But I can not see anything in the scene, is there something wrong?

**Comment by zhangweizhe** [comment]
@liaxim I can get you point, Thank you
