### ISSUE TITLE
Black screen of the video for gvr-vuforia

### ISSUE THREAD

**Issue by PsycoTodd** [gearvrf/GearVRf-Demos#49]
Hello guys,
Just want to ask for some suggestions on this issue. When debugging in develop mode with gvf-vuforia sample, there are frequently cases where the camera video texture failed to show in the background, which leads to a pitch black app. However, the teapot can be drawn once it detects the image target, so I feel it is a fail loading texture issue. In the onStep function, I saw that the bindVideoBackgroundTexture(0) and there is another setVideoBackgroundTextureID, which assign the draw location of the vuforia live cam to the passThroughTexture. May be something here is not happened in GL thread?

Hope you have some suggestions. thank you.

**Comment by liaxim** [comment]
Hi,

setVideo is called by createPassthrough which is called by onInit so it is on the GL thread. onStep is on the GL thread too.

Another possibility is that the Vuforia initialization failed and the vuforiaState in VuforiaSampleActivity is not having a good value. If that happens, you would end up with a black screen too.

If this keeps occuring, please collect the logcat output and send it over to us.

**Comment by liaxim** [comment]
Can we close this one as I think the same issue is tracked under https://github.com/gearvrf/GearVRf-Demos/issues/53? Thanks.
