### ISSUE TITLE
ComplexScene: Add preference for number of bunnies?

### ISSUE THREAD

**Issue by danke-sra** [gearvrf/GearVRf-Demos#50]
Can we add an application preference for the complex scene app?

That will allow testers to change the number of bunnies to be rendered. Some reference is here: http://code.tutsplus.com/tutorials/android-essentials-application-preferences--mobile-2914

**Comment by liaxim** [comment]
You most certainly know that you can make the change if you feel like it. Seems like most people are fine with rebuilding the sample.

Why don't we move this sample under Framework/Tools or something? It is not a real sample..

**Comment by danke-sra** [comment]
Teresa is working on this. This ticket is to track related issues. I am fine with adding some apps to Tools. What do others think?

**Comment by danke-sra** [comment]
@teresa-mao How is this going?

**Comment by teresa-mao** [comment]
@danke-sra I apologize for the delay, you will have it this week.

**Comment by liaxim** [comment]
Do we still care about this?

**Comment by danke-sra** [comment]
Let's cancel this issue. There are other ways to configure the app now.
