### ISSUE TITLE
gvr-Vuforia cannot render camera video.

### ISSUE THREAD

**Issue by PsycoTodd** [gearvrf/GearVRf-Demos#53]
Hello guys,
Just recently notice that it is really difficult to run the demo of gvr-Vuforia to load the camera live video at the background. The major result is a black screen. However, the vuforia image tracking still works so the teapot can be drawn without any issue. But the video just cannot be displayed. Hope to know what the reason could be. 

Thank you in advance!

TODD

**Comment by thomasflynn** [comment]
@liaxim, @teresa-mao, any ideas?

**Comment by PsycoTodd** [comment]
Hello guys
I think the issue is, in private void createCameraPassThrough(), Renderer.getInstance().setVideoBackgroundTexutreID(passThroughTexture.getId()) failed. Actually the passThroughTexture.getId() returns a non-zero id, so I suppose this is fine. But setVideoBackgroundTexutreID return false.

**Comment by PsycoTodd** [comment]
OK, I think that put the createCameraPassThrough() in onInit(GVRContext gvrContext) could be too early when Vuforia somehow is not ready. Put it after the splash screen might help. However, I still not sure about this. Need to test more to see if there is still case when the live camera fails.

**Comment by liaxim** [comment]
Please try this out: https://github.com/liaxim/GearVRf-Demos/tree/vuforia-sample and let us know. Thanks.

**Comment by liaxim** [comment]
Btw, if Vuforia is not properly initialized calling any of the APIs would lead to immediate crash as they do not allow access.

**Comment by PsycoTodd** [comment]
Hello liaxim
Thank you for your help. I notice that tree/vufroia-sample might be a fix for this issue. Could you briefly tell me what you have changed? I will test it to see if the failed live camera happens or not.

**Comment by liaxim** [comment]
Sure; the changes are:

- wait until vuforia's initialization is complete before initiating the createCameraPassThrough(); assuming that setVideoBackground may fail in case vuforia is in process of initialization.

- remove the splash screen as it requires use of some awkward apis that could lead to errors that result in the very same black screen you are seeing; to put it shortly, we have this concept of a mainScene but if you use the splashScreen you get two of these and you might be adding your scene objects to a scene that is not active hence nothing becomes visible.

- update the sample from Vuforia SDK 5.0 to 5.5 hoping we may pick up some bug fixes along the way.

**Comment by PsycoTodd** [comment]
Hello liaxim

Just a quick question, is there a way to clear the video scene object's texture? Or does GVRTexture contain a way to clear the pixels? I need to switch between different videos with one video scene object and I notice that the previous video's texture may hold at the beginning of loading of the next video. Hope there is a way to clear the first one. Or do I need to recreate another video scene object?

Thank you.

**Comment by liaxim** [comment]
If you are referring to GVRVideoSceneObject, no, probably you can't. It is using an external texture and TexSubImage2D for example is not supported according to the specification. I think re-creating is the way to go.

**Comment by PsycoTodd** [comment]
@liaxim  I have tried your updated version  https://github.com/liaxim/GearVRf-Demos/tree/vuforia-sample, it seems work now without black background. BTW, if you can try to update the far clipping plane to be further (I set it to 10000), and disable the depth test of the background plane that would be great.

**Comment by liaxim** [comment]
Created a pull request with the additional tweaks you requested: https://github.com/gearvrf/GearVRf-Demos/pull/58.

**Comment by liaxim** [comment]
@PsycoTodd Can we consider this issue resolved?

**Comment by PsycoTodd** [comment]
@liaxim yes, I think so.
