### ISSUE TITLE
Is gvr-blurfilter still working? 

### ISSUE THREAD

**Issue by ragner** [gearvrf/GearVRf-Demos#623]
I am trying implement a two passes shader to add effects to final texture like a blur
but I am failing.

I have seen that blurfilter demo but looks that its last pass is just overriding the result
of previous pass. It is not composing to have the final result.

What is the best practice to add two passes blur shader to a scene object?

**Comment by apjagdale** [comment]
@ragner I have made PR for Framework (PR1929) and Demo (PR625). Do let me know if it works for you.

**Comment by ragner** [comment]
Hi @apjagdale I looks not working yet. 
Doesn't should apply VertBlurShader on result of previous HorzBlurShader?

It looks that only the last shader VertBlurShader is working and the result of HorzBlurShader was discard.

**Comment by apjagdale** [comment]
@ragner Could you check with my new changes to the demo. I modified the shader for second post effect.

**Comment by ragner** [comment]
Hi @apjagdale,
is looks working now.
Just a comment about GVRRenderTarget#setEnable(false) that looks not working.
How could I "pause" the GVRRenderTarget?

**Comment by ragner** [comment]
One more question:

I would like to use it with a image that has some transparency but the
the transparent area is getting black ...

How could I fix this?

**Comment by apjagdale** [comment]
@ragner It does pauses for me on calling setEnable(false) on GVRRenderTarget. When paused it just shows the last rendered image.

**Comment by apjagdale** [comment]
@ragner Are you using the transparent texture for 2 pass filter or as an object inside the scene?

**Comment by ragner** [comment]
@apjagdale It is a GVRViewSceneObject in the scene. It has a transparent background.
The blur shader is working fine but the background is getting black.

**Comment by ragner** [comment]
Hi @apjagdale,
refer to my brach https://github.com/ragner/GearVRf-Demos/tree/blurfilterFix
It shows my issue.

**Comment by ragner** [comment]
Hi @apjagdale,
I would like to have something like this code https://github.com/ragner/GearVRf-Demos/tree/blurfilter2Pass working ...

Could you help me with this?

**Comment by apjagdale** [comment]
@ragner So two changes need to be done.
1. Set background color of blur scene to Red.
2. Modify both the post effect shaders so they preserve the original alpha values.
    Change:
    ```
   vec4 vertBlur(vec2 texCoord, vec2 resolution)
    {
        float offset[3], weight[3];
        offset[0] = 0.0;
        offset[1] = 1.3846153846;
        offset[2] = 3.2307692308;
        weight[0] = 0.2270270270;
        weight[1] = 0.3162162162;
        weight[2] = 0.0702702703;
        vec4 original = texture(u_texture, texCoord);

        vec3 tc = original.rgb * weight[0];
        for (int i = 1; i < 3; i++)
        {
            tc += texture(u_texture, texCoord + vec2(0.0, offset[i]) / resolution.y).rgb * weight[i];
            tc += texture(u_texture, texCoord - vec2(0.0, offset[i]) / resolution.y).rgb * weight[i];
        }
        return vec4(tc, original.a);
    }
    ```

**Comment by liaxim** [comment]
This I believe has been fixed. Let me know if otherwise.
