### ISSUE TITLE
How could I press the RUN button.

### ISSUE THREAD

**Issue by 02170916** [gearvrf/GearVRf-Demos#638]
I have started using GearVRf-Demos. I'm looking your  'Getting Started' page and everything are getting fine without one point. I can't press the RUN button. The button color is gray and can't press. I need your help!!

**Comment by liaxim** [comment]
Hi. Which version of Android Studio are you using? Did you import the correct project? GearVRf-Demos should be the folder you select to import in AS. Please also invoke the "File->Sync Project with Gradle Files" command.

**Comment by 02170916** [comment]
Thanks for your reply.  I'm using Version 3.1.4 of AS.  I selected 'Open an existing Android Studio project' and opened GearVRf-Demos-master folder.  I pressed 'Sync Project with Cradle Files' but failed with error message 'Gradle project sync failed.Basic functionality(e.g. editing, debugging) will not work properly.'

**Comment by liaxim** [comment]
Ok, found the problem. Please download the demos and try again.

**Comment by 02170916** [comment]
The project was successfully builded and installed in my smartphone!! Thank you!!

**Comment by liaxim** [comment]
@02170916 Can we close the issue?

**Comment by 02170916** [comment]
Yes, please. Thanks!
