### ISSUE TITLE
IllegalStateException in immersivepedia

### ISSUE THREAD

**Issue by liaxim** [gearvrf/GearVRf-Demos#9]
I was just clicking around in the Dinosaur scene (with the video playing).

```
01-05 11:13:01.538 15935 16020 E AndroidRuntime: FATAL EXCEPTION: GLThread 1442
01-05 11:13:01.538 15935 16020 E AndroidRuntime: Process: org.gearvrf.immersivepedia, PID: 15935
01-05 11:13:01.538 15935 16020 E AndroidRuntime: java.lang.IllegalStateException
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at android.media.MediaPlayer.getDuration(Native Method)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.immersivepedia.videoComponent.VideoComponent.getDuration(VideoComponent.java:186)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.immersivepedia.model.VideoDinosaurGroup.onStep(VideoDinosaurGroup.java:91)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.immersivepedia.scene.DinosaurScene.onStep(DinosaurScene.java:102)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.immersivepedia.MainScript.onStep(MainScript.java:67)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.GVRViewManager.beforeDrawEyes(GVRViewManager.java:567)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.GVRViewManager.drawFrame(GVRViewManager.java:511)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.GVRViewManager.access$0(GVRViewManager.java:506)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.GVRViewManager$3.onDrawFrame(GVRViewManager.java:498)
01-05 11:13:01.538 15935 16020 E AndroidRuntime:    at org.gearvrf.GVRViewManager.onDrawFrame(GVRViewManager.java:364)
```

**Comment by deepakrawat22** [comment]
Observed a segmentation fault in immersivepedia app while playing/pausing video:

`07-05 15:50:50.416 393-393/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-05 15:50:50.416 393-393/? A/DEBUG: Build fingerprint: 'samsung/trlteuc/trlteatt:6.0.1/MMB29M/N910AUCU2EPE5:user/release-keys'
07-05 15:50:50.416 393-393/? A/DEBUG: Revision: '12'
07-05 15:50:50.416 393-393/? A/DEBUG: ABI: 'arm'
07-05 15:50:50.416 393-393/? A/DEBUG: pid: 11135, tid: 11909, name: GLThread 23940  >>> com.samsung.android.gvr.sample <<<
07-05 15:50:50.416 393-393/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8d
07-05 15:50:50.446 393-393/? A/DEBUG:     r0 9f279c9c  r1 93c3d9f0  r2 a9a86bf3  r3 00000000
07-05 15:50:50.446 393-393/? A/DEBUG:     r4 99719a70  r5 94aff218  r6 94aff21c  r7 9f279c9c
07-05 15:50:50.456 393-393/? A/DEBUG:     r8 9f279d88  r9 00000000  sl 00000000  fp 9f279c84
07-05 15:50:50.456 393-393/? A/DEBUG:     ip 9f279970  sp 9f279c60  lr 9f27997c  pc 9ff02eb0  cpsr 200f0010
07-05 15:50:50.466 393-393/? A/DEBUG: backtrace:
07-05 15:50:50.466 393-393/? A/DEBUG:     #00 pc 00094eb0  /data/app/com.samsung.android.gvr.sample-1/lib/arm/libgvrf.so (_ZN3gvr6Picker9pickSceneEPNS_5SceneERSt6vectorINS_12ColliderDataESaIS4_EEffffff+504)
07-05 15:50:50.476 393-393/? A/DEBUG:     #01 pc 000951c0  /data/app/com.samsung.android.gvr.sample-1/lib/arm/libgvrf.so (Java_org_gearvrf_NativePicker_pickScene+92)
07-05 15:50:50.476 393-393/? A/DEBUG:     #02 pc 00273137  /data/data/com.samsung.android.gvr.sample/cache/slice-slice_1-classes.dex (offset 0x146000) (long[] org.gearvrf.NativePicker.pickScene(long, float, float, float, float, float, float)+162)
07-05 15:50:50.476 393-393/? A/DEBUG:     #03 pc 001fd66f  /data/data/com.samsung.android.gvr.sample/cache/slice-slice_1-classes.dex (offset 0x146000) (org.gearvrf.GVREyePointeeHolder[] org.gearvrf.GVRPicker.pickScene(org.gearvrf.GVRScene, float, float, float, float, float, float)+698)
07-05 15:50:50.476 393-393/? A/DEBUG:     #04 pc 001fd357  /data/data/com.samsung.android.gvr.sample/cache/slice-slice_1-classes.dex (offset 0x146000) (org.gearvrf.GVREyePointeeHolder[] org.gearvrf.GVRPicker.pickScene(org.gearvrf.GVRScene)+226)
07-05 15:50:50.476 393-393/? A/DEBUG:     #05 pc 0002ce97  /data/data/com.samsung.android.gvr.sample/cache/slice-slice_3-classes.dex (offset 0x2c000) (void org.gearvrf.immersivepedia.focus.FocusableController.process(org.gearvrf.GVRContext)+154)
07-05 15:50:50.476 393-393/? A/DEBUG:     #06 pc 002dee13  /data/data/com.samsung.android.gvr.sample/cache/slice-slice_1-classes.dex (offset 0x146000) (void org.gearvrf.immersivepedia.Main.onStep()+158)
07-05 15:50:50.476 393-393/? A/DEBUG:     #07 pc 000e6411  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
07-05 15:50:50.476 393-393/? A/DEBUG:     #08 pc 004037cd  /system/lib/libart.so (art_quick_invoke_stub+188)
07-05 15:50:50.476 393-393/? A/DEBUG:     #09 pc 001020e4  [stack:11909]`

Will work on resolving both issues.

**Comment by deepakrawat22** [comment]
GearVRf #673 fixes the SIGSEGV issue

**Comment by deepakrawat22** [comment]
@liaxim I tried reproducing IllegalStateException issue but it never happened in my case. Is there a particular way to reproduce this one or is it a rare issue ?

**Comment by liaxim** [comment]
Just started the video and began randomly to click around. The MediaPlayer state diagram might be helpful: https://developer.android.com/reference/android/media/MediaPlayer.html#StateDiagram

**Comment by liaxim** [comment]
Too old
